/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTicketListIndexRouteImport } from './routes/_authenticated/ticket-list/index'
import { Route as AuthenticatedOdataIndexRouteImport } from './routes/_authenticated/odata/index'
import { Route as AuthenticatedAddTicketIndexRouteImport } from './routes/_authenticated/add-ticket/index'
import { Route as UnauthenticatedAuthRegisterRouteImport } from './routes/_unauthenticated/auth/register'
import { Route as UnauthenticatedAuthLoginRouteImport } from './routes/_unauthenticated/auth/login'
import { Route as UnauthenticatedAuthForgotPasswordRouteImport } from './routes/_unauthenticated/auth/forgot-password'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketListIndexRoute =
  AuthenticatedTicketListIndexRouteImport.update({
    id: '/ticket-list/',
    path: '/ticket-list/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOdataIndexRoute = AuthenticatedOdataIndexRouteImport.update({
  id: '/odata/',
  path: '/odata/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAddTicketIndexRoute =
  AuthenticatedAddTicketIndexRouteImport.update({
    id: '/add-ticket/',
    path: '/add-ticket/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const UnauthenticatedAuthRegisterRoute =
  UnauthenticatedAuthRegisterRouteImport.update({
    id: '/auth/register',
    path: '/auth/register',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedAuthLoginRoute =
  UnauthenticatedAuthLoginRouteImport.update({
    id: '/auth/login',
    path: '/auth/login',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedAuthForgotPasswordRoute =
  UnauthenticatedAuthForgotPasswordRouteImport.update({
    id: '/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth/forgot-password': typeof UnauthenticatedAuthForgotPasswordRoute
  '/auth/login': typeof UnauthenticatedAuthLoginRoute
  '/auth/register': typeof UnauthenticatedAuthRegisterRoute
  '/add-ticket': typeof AuthenticatedAddTicketIndexRoute
  '/odata': typeof AuthenticatedOdataIndexRoute
  '/ticket-list': typeof AuthenticatedTicketListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/auth/forgot-password': typeof UnauthenticatedAuthForgotPasswordRoute
  '/auth/login': typeof UnauthenticatedAuthLoginRoute
  '/auth/register': typeof UnauthenticatedAuthRegisterRoute
  '/add-ticket': typeof AuthenticatedAddTicketIndexRoute
  '/odata': typeof AuthenticatedOdataIndexRoute
  '/ticket-list': typeof AuthenticatedTicketListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_unauthenticated/auth/forgot-password': typeof UnauthenticatedAuthForgotPasswordRoute
  '/_unauthenticated/auth/login': typeof UnauthenticatedAuthLoginRoute
  '/_unauthenticated/auth/register': typeof UnauthenticatedAuthRegisterRoute
  '/_authenticated/add-ticket/': typeof AuthenticatedAddTicketIndexRoute
  '/_authenticated/odata/': typeof AuthenticatedOdataIndexRoute
  '/_authenticated/ticket-list/': typeof AuthenticatedTicketListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/add-ticket'
    | '/odata'
    | '/ticket-list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/add-ticket'
    | '/odata'
    | '/ticket-list'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/'
    | '/_unauthenticated/auth/forgot-password'
    | '/_unauthenticated/auth/login'
    | '/_unauthenticated/auth/register'
    | '/_authenticated/add-ticket/'
    | '/_authenticated/odata/'
    | '/_authenticated/ticket-list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ticket-list/': {
      id: '/_authenticated/ticket-list/'
      path: '/ticket-list'
      fullPath: '/ticket-list'
      preLoaderRoute: typeof AuthenticatedTicketListIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/odata/': {
      id: '/_authenticated/odata/'
      path: '/odata'
      fullPath: '/odata'
      preLoaderRoute: typeof AuthenticatedOdataIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/add-ticket/': {
      id: '/_authenticated/add-ticket/'
      path: '/add-ticket'
      fullPath: '/add-ticket'
      preLoaderRoute: typeof AuthenticatedAddTicketIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unauthenticated/auth/register': {
      id: '/_unauthenticated/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof UnauthenticatedAuthRegisterRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/auth/login': {
      id: '/_unauthenticated/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof UnauthenticatedAuthLoginRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/auth/forgot-password': {
      id: '/_unauthenticated/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof UnauthenticatedAuthForgotPasswordRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAddTicketIndexRoute: typeof AuthenticatedAddTicketIndexRoute
  AuthenticatedOdataIndexRoute: typeof AuthenticatedOdataIndexRoute
  AuthenticatedTicketListIndexRoute: typeof AuthenticatedTicketListIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAddTicketIndexRoute: AuthenticatedAddTicketIndexRoute,
  AuthenticatedOdataIndexRoute: AuthenticatedOdataIndexRoute,
  AuthenticatedTicketListIndexRoute: AuthenticatedTicketListIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedAuthForgotPasswordRoute: typeof UnauthenticatedAuthForgotPasswordRoute
  UnauthenticatedAuthLoginRoute: typeof UnauthenticatedAuthLoginRoute
  UnauthenticatedAuthRegisterRoute: typeof UnauthenticatedAuthRegisterRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedAuthForgotPasswordRoute:
    UnauthenticatedAuthForgotPasswordRoute,
  UnauthenticatedAuthLoginRoute: UnauthenticatedAuthLoginRoute,
  UnauthenticatedAuthRegisterRoute: UnauthenticatedAuthRegisterRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
